### ISSUE TITLE
Javascript vector graphics library

### ISSUE THREAD

**Issue by Bondifrench** [shivkumarganesh/InfoVizGeek#1]
You should add this one to your list:
https://github.com/andreaferretti/paths-js

License is Apache 2.0 from what I can see

**Comment by shivkumarganesh** [comment]
Hi Dominik,
I have included the library as mentioned by you. Let me know if you have other libraries to be added to the list. 

Link to the list is as follows:-
https://github.com/shivkumarganesh/InfoVizGeek#other-useful-javascript-components

Regards,
Shiv
